### ISSUE TITLE
Schedule automated backup of docs

### ISSUE THREAD

**Issue by ejfrancis** [prosemeteor/prosemirror#12]
We need a way to define an interval (as an option that a user can change) in which documents are backed up so that work isn't lost, and so that later on users can revert to previous snapshots.

**Comment by funkyeah** [comment]
By user do you mean integrator of the package? I think it would be pretty tough to do it on a per user basis.

Looking at Google Docs they do some interesting things. It appears they "save" on almost every edit. But edits that are in close proximity to each other timewise are compacted into a single revision.

**Comment by ejfrancis** [comment]
Yeah the integrator. We could definitely add an option to store on every keystroke, but it'd be good to enable less frequent writes to lessen db load as well if you're running on a budget.
