### ISSUE TITLE
collab module connection lost edge case

### ISSUE THREAD

**Issue by funkyeah** [prosemeteor/prosemirror#2]
Saw this [question](https://discuss.prosemirror.net/t/how-to-handle-edge-case-with-collab-module/288) on the forum and thought its resolution should be tracked.

**Comment by ejfrancis** [comment]
looks like it was closed, see [Issue #307](https://github.com/prosemirror/prosemirror/issues/307)

the collab guide has been updated to reflect the change, now the authority takes a clientID for each mutation as well (see `Authority.prototype.receiveSteps`)

**Comment by ejfrancis** [comment]
note that as of right now, that change is in prosemirror's master branch but isn't published to npm yet. on my branch I've just pulled down the latest prosemirror master, built it, and checked it in for now
