### ISSUE TITLE
License and Contribution Guide

### ISSUE THREAD

**Issue by ejfrancis** [prosemeteor/prosemirror#6]
Before we get too far we should get a license file (LICENSE.txt) and contributing guide (CONTRIBUTING.md) into the repo. I've put together a draft for a [contributing guide](https://humon.com/Prosemeteor/RJsnS9dyAH8k6cuma/Contributing/sqaTwYocYRn4f9tAK), let's discuss that and the proper license to choose.

@funkyeah

**Comment by ejfrancis** [comment]
I don't know much about OS licenses tbh. A few helpful links I've found

https://opensource.org/licenses 
http://choosealicense.com/
https://www.smashingmagazine.com/2010/03/a-short-guide-to-open-source-and-similar-licenses/

**Comment by funkyeah** [comment]
Prosemirror and Meteor are both MIT licensed which allows us to license
Prosemeteor pretty much however we want. I think the two best options are
probably MIT and/or GPL3.

GPL is best if you share the FSF's philosophical stance about free
software. MIT is among the best best if there will never be any intention
to directly commercialize the project and want as many people as possible
to use it. If we'd like to keep commercialization as an option then I think
a dual license model is the best. E.g. it's GPL3 by default but if you want
to integrate it into a commercial closed-source application then you can
purchase a more permissive license like MIT or Apache.

**Comment by ejfrancis** [comment]
I'm not worried about commercialization personally, but I may be biased because I plan on using this in a closed-source app. I like the idea of MIT, letting anyone do pretty much whatever they want with it. What do you think?

**Comment by ejfrancis** [comment]
@funkyeah for the MIT license, it requires the holder's name/holding company. should we just put our names as the holders?

**Comment by funkyeah** [comment]
Sure that works for me
