### ISSUE TITLE
Service Discovery for multiple app servers

### ISSUE THREAD

**Issue by ejfrancis** [prosemeteor/prosemirror#8]
For any document, there can only ever exist one Authority to track its state in memory. If an application is deployed with multiple app servers and another server already has an Authority for a doc, we need a way to find the IP of the server hosting that doc's Authority so that a client can connect to that particular server and receive traffic from it.

Requirements:
- [x] when a server starts up, it register's itself as a server that can host Authorities. "Here's my IP, I'm ready to host an Authority."
- [x] if a server shuts down, remove its IP from the registry since it's no longer available
- [x] when a client opens a doc, that client's app server asks the central registry "Are there any servers currently hosting an Authority for doc XXX?" 
  - [x] if there is one, get its IP from the registry db and return it to the client, so the client can set up a DDP connection to that server (`DDP.connect()`)
  - [x] if there isn't one, pick a server IP to host the Authority from the registry (round-robin selection algorithm should work), tell that server to create an Authority, and return that server's IP so the client can set up a DDP connection
- [x] make all client DDP interactions (Meteor Methods, Streamer) use the connection set up from the IP given back by the Authority

Authority registry db collection would look something like this

```
{ 
   _id: 'abc1234',
   authorityIp: '123.456.7.8',
   docIds: ['docA','docC','docD']
}
{ 
   _id: 'xyz4321',
   authorityIp: '876.543.2,1',
   docIds: ['docE','docF']
}
{ 
   _id: 'plo9876',
   authorityIp: '643.721.8.4',
   docIds: []
}
```

For the round robin selection, since multiple independent servers will be choosing them, we may want to store information about the last server chosen in db. Something like

```
{
   ipOfLastAuthoritySelected: '632.11.4.5'
}
```

**Comment by ejfrancis** [comment]
package for getting ip address https://www.npmjs.com/package/ip

**Comment by ejfrancis** [comment]
I've just put up a PR to the RocketChat `meteor-streamer` package to allow setting up a DDP connection to an alternate server, see [the pull request](https://github.com/RocketChat/meteor-streamer/pull/5)

**Comment by funkyeah** [comment]
Looks like it's already been accepted. Nice!

**Comment by ejfrancis** [comment]
yeah that was quick 😄

**Comment by ejfrancis** [comment]
I've started work for this, it's on my [feature/authority-registry branch](https://github.com/ejfrancis/prosemirror/tree/feature/authority-registry/lib/imports/api/authority-registry) if anyone would like to follow along. It's going to take awhile to complete

**Comment by ejfrancis** [comment]
Alright so my plan was to have an Authority just unregister itself from the registry when it shuts down, but it turns out Meteor doesn't offer any pre-shutdown hook. So instead my plan is to do something like this
1. When an app server starts up, it register itself as available to host Authorities 
2. A client requests to open a document that nobody else is currently editing
3. AuthorityManager on that client's app server asks the AuthorityRegistry to choose a server to host this document's Authority
4. AuthorityRegistry chooses a server IP from its collection of available servers to host Authorities, and makes a health check request to see if the server is up and running
   1. if the selected server is up, tell it to create an Authority and let the client know to connect to that Authority
   2. if the selected server is down, record that in the registry db as a failed attempt
5. Next time that server that failed the health check gets picked by the AuthorityRegistry again, if it's up and running we're good, remove the failed attempt from db. If it fails again, see how many times it failed previously. If it failed X times (4 or 5 maybe?) we assume that server is offline, and we remove it from the registry
6. When that app server that went down is replaced, it will register itself as available to host Authorities on its startup

**Comment by ejfrancis** [comment]
Server side implementation is mostly done in my feature branch `feature/authority-registry`, it's keeping track of all servers that are up, and running health checks on an interval to make sure to remove servers that have gone down for some reason. GroupIds are taken into account as well, so all docs marked with the same `groupId` will be hosted on the same server. There is a Meteor method `ProseMeteor.getUrlOfAuthorityHostingDoc` that a client can call to get the url of the authority to connect to.

Next step is to have the client call the method, set up a new DDP connection to that server, and use that connection on the client for all interactions with the authority.

**Comment by ejfrancis** [comment]
Alright this is _mostly_ done, it's all up in my feature branch. Pretty big change across the codebase, both client and server. The [groupIds implementation](https://github.com/prosemeteor/prosemirror/issues/20) is all included in this as well since it's part of the core service discovery logic. Expect a PR soon.

**Comment by ejfrancis** [comment]
Right now docIds and groupIds are never marked as removed from the authority registry database. That will be part of [Issue 18's](https://github.com/prosemeteor/prosemirror/issues/18) implementation.
